Repository Stratio/cluster-api-provider-gcp, pull requests merged in 2024-10, with the labels that each got.

#15 [PLT-806] GKE nodos privados
  CHANGELOG.md
  cloud/services/container/clusters/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: ok-to-merge, 0.2.0

#19 [Fix] CVE-2024-34156
  Dockerfile
  go.mod
  hack/tools/go.mod
Labels: ok-to-test, 0.2.0

#18 Set grype scan test as true by default
  Jenkinsfile
Labels: ok-to-merge, 0.2.0, skip doGrypeScan, skip doEmptyLines

#20 [PLT-911] External Endpoint disabled
  cloud/services/container/clusters/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
  manifests/infrastructure-components.yaml
  manifests/metadata.yaml
Labels: ok-to-merge, 0.2.0, need-cherry-pick-main

#22 Update CHANGELOG.md
  CHANGELOG.md
Labels: wip, 0.2.0, skip doGrypeScan, skip doEmptyLines, skip deadExternalLinks, skip doLanguageCheck, skip doOrphanAssets, skip doStratioDocsChecks

#24 [PLT-988] Added github action to push infrastructure-components.yaml and metadata.yaml
  .github/workflows/release.yml
Labels: 0.2.0

#26 [PLT-965] [GKE] Deshabilitar monitorización/logs gestionada
  CHANGELOG.md
  cloud/services/container/clusters/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: 0.2.0, need-cherry-pick-main

#27 [PLT-327] [GKE] Force sync to 2m
  manifests/infrastructure-components.yaml
Labels: 0.2.0, need-cherry-pick-main

#28 [Modify manager to GitHub actions]
  config/manager/manager.yaml
Labels: 0.2.0

#29 [PLT-965] Cherry master
  CHANGELOG.md
  cloud/services/container/clusters/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  config/manager/manager.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: ok-to-review, 0.2.0

#30 Update CHANGELOG.md
  CHANGELOG.md
Labels: main
