Repository Stratio/cluster-api-provider-gcp, pull requests merged in 2025-01, with the labels that each got.

#37 [PLT-1330] CMEK, SA & CIDRs (Cherry to master)
  CHANGELOG.md
  cloud/scope/managedmachinepool.go
  cloud/services/container/clusters/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedmachinepools.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
  exp/api/v1beta1/gcpmanagedcontrolplane_webhook.go
  exp/api/v1beta1/gcpmanagedmachinepool_types.go
  exp/api/v1beta1/types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
Labels: ok-to-merge, 0.4.0

#38 [PLT-1332] [GKE] Validaciones parámetros GKE
  cloud/services/container/clusters/reconcile.go
  go.mod
  go.sum
Labels: 0.3.0

#39 Feature/plt 1496 add support extended channel
  CHANGELOG.md
  Makefile
  cloud/services/container/clusters/reconcile.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedmachinepools.yaml
  config/rbac/role.yaml
  exp/api/v1beta1/gcpmanagedcontrolplane_types.go
  go.mod
  go.sum
Labels: ok-to-test, 0.4.0
